Initial release
mykaarma/Daksha pull request #1
Opened 2021-04-12 09:30 UTC by prakashiit

2021-04-12 09:51 UTC, SriMouli requested changes
verify is [pep8](https://www.python.org/dev/peps/pep-0008/) is follwed

2021-04-12 09:51 UTC, SriMouli commented on Dockerfile
> +# Install any needed packages specified in requirements.txt
Dockerfile is incomplete. move items from docker-compose to here

2021-04-12 09:51 UTC, SriMouli commented on README.md
> +### Using docker-compose
change to using docker

2021-04-12 09:51 UTC, SriMouli commented on README.md
> +Copyright 2020 myKaarma
change to 2021

2021-04-12 09:51 UTC, SriMouli commented on daksha/settings.py
> +SECRET_KEY = 'gj%7t91&c$*q&+fkx-wuug^i$0b@@lk26vd4txdq=)%_319hyy'
change to env

2021-04-12 09:51 UTC, SriMouli commented on daksha/settings.py
> +ALLOWED_HOSTS = [
is env support present for this?

2021-04-12 09:51 UTC, SriMouli commented on daksha/settings.py
> +    # 'django.middleware.csrf.CsrfViewMiddleware',
remove commented

2021-04-12 09:51 UTC, SriMouli commented on docker-compose.yml
> +    command: bash -c "python manage.py runserver 0.0.0.0:8000"
use wsgy or some webServer. runserver is not prod ready

2021-04-12 09:51 UTC, SriMouli commented on docker-compose.yml
> +      - /var/log/kaarya/:/var/log/kaarya/
remove this

2021-04-12 09:51 UTC, SriMouli commented on engine/email_generator.py
> +def send_email_postmark(subject, message, recipient_email):
change to support any generic smtp client

2021-04-12 09:51 UTC, SriMouli commented on engine/selenium_code.py
> +"""
rename to selenium_helper  or suitable name

2021-04-20 16:39 UTC, rajatsharda04 commented on README.md
> +### Using docker-compose
done

2021-04-20 16:48 UTC, rajatsharda04 commented on engine/selenium_code.py
> +"""
Done

2021-04-20 16:48 UTC, rajatsharda04 commented on docker-compose.yml
> +      - /var/log/kaarya/:/var/log/kaarya/
Done

2021-04-20 16:48 UTC, rajatsharda04 commented on daksha/settings.py
> +    # 'django.middleware.csrf.CsrfViewMiddleware',
Done

2021-04-20 16:48 UTC, rajatsharda04 commented on README.md
> +Copyright 2020 myKaarma
Done

2021-04-20 16:55 UTC, rajatsharda04 commented on daksha/settings.py
> +SECRET_KEY = 'gj%7t91&c$*q&+fkx-wuug^i$0b@@lk26vd4txdq=)%_319hyy'
Done

2021-04-22 11:42 UTC, rajatsharda04 commented on docker-compose.yml
> +    command: bash -c "python manage.py runserver 0.0.0.0:8000"
Done

2021-04-22 11:59 UTC, rajatsharda04 commented on daksha/settings.py
> +ALLOWED_HOSTS = [
Done

2021-04-23 10:34 UTC, rajatsharda04 commented on Dockerfile
> +# Install any needed packages specified in requirements.txt
Added run CMD to docker file.

2021-04-23 10:37 UTC, rajatsharda04 commented on engine/email_generator.py
> +def send_email_postmark(subject, message, recipient_email):
Created issue https://github.com/mykaarma/Daksha/issues/2

2021-04-28 18:14 UTC, SriMouli approved these changes

2021-04-28 18:14 UTC, SriMouli commented on docker-compose.yml
> +      APACHE_URL: ""
add some sensible defaults where possible.

2021-05-17 06:32 UTC, merged