Issue 18
mykaarma/daksha pull request #40
Opened 2022-07-01 18:17 UTC by pulkitsinghall

## Description

## Motivation and Context

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have Extended README or added documentation/comments where applicable
- [ ] Added copyright headers for new files from CONTRIBUTING.md
- [ ] My code follows the code style of this project.

- [ ] I have read the [contributing guidelines](CONTRIBUTING.md).
- [ ] I have updated the [ChangeLog](CHANGELOG.md) following [Semantic Versioning](https://semver.org)

2022-07-10 05:13 UTC, Rishi16royy approved these changes

2022-07-10 12:11 UTC, hriddhighosh4 requested changes

2022-07-10 12:11 UTC, hriddhighosh4 commented on ChromeExtension/src/index.js
> +            let windowOfNewTab = window.open("https://www.google.com");
Element name should be changed from a

2022-10-20 04:20 UTC, hriddhighosh4 approved these changes

2022-10-20 04:21 UTC, merged