Including database feature
mykaarma/daksha pull request #51
Opened 2023-05-29 17:04 UTC by Prashastmykaarma

include the database feature in such a way that the existing functionality of Daksha remains as it is and if someone wants to save the test data in Daksha then he can set it up as well.

2023-05-30 07:15 UTC, hriddhighosh4 commented on engine/models.py
> +class ResultStored(models.Model):
makes this TestResults

2023-05-30 07:16 UTC, hriddhighosh4 commented on engine/executor.py
> +        if(settings.TEST_RESULT_DB != None and settings.TEST_RESULT_DB == "postgres"):
Add equalsIgnoreCase

2023-05-30 07:18 UTC, hriddhighosh4 commented on engine/executor.py
> +
make a method save_result_ib_db

2023-05-30 07:19 UTC, hriddhighosh4 commented on engine/test_result_initializer.py
> +        logger.info("Initializing the entry in database of the abovestated test")
only test_result

2023-05-30 07:20 UTC, hriddhighosh4 commented on engine/models.py
> +        self.initialized_test_result=initialized_test_result
self.test_result

2023-05-30 07:20 UTC, hriddhighosh4 commented on engine/models.py
> +    def __init__(self, index, test_id, variable_dict, test_yml, web_driver , initialized_test_result):
test_result

2023-06-01 10:38 UTC, hriddhighosh4 commented on README.md
> + - We only support Postgresql database at this point. To enable this one has to set the environment        variable TEST_RESULT_DB to "postgres".
why is there extra space?

2023-06-01 10:42 UTC, hriddhighosh4 requested changes

2023-06-01 10:42 UTC, hriddhighosh4 commented on README.md
> +### Deploying with Docker
Deploying  Daksha with DB enabled by Docker

2023-06-01 11:17 UTC, hriddhighosh4 requested changes

2023-06-01 11:17 UTC, hriddhighosh4 commented on CHANGELOG.md
> +1. Added the database feature in such a way that the existing functionality of Daksha remains as it
1. Added Database for Test Results in Daksha.
2. Now users can opt for test results to be saved in a Postgres database

2023-06-01 11:22 UTC, hriddhighosh4 commented on engine/test_result_utils.py
> +        test_result.TestUUId=test_id
UUID

2023-06-01 11:40 UTC, AlphaRahul16 submitted a review, later dismissed

2023-06-01 11:59 UTC, Rishi16royy commented on README.md
> + TEST_RESULT_DB, PG_DB, PG_USER, PG_PASSWORD, PG_HOST, PG_PORT
add code format like `TEST_RESULT_DB `

2023-06-01 11:59 UTC, Rishi16royy commented on README.md
> + TEST_RESULT_DB, PG_DB, PG_USER, PG_PASSWORD, PG_HOST, PG_PORT
text should be enclosed by ` . Do this in all the places where env variables are mentioned

2023-06-01 11:59 UTC, Rishi16royy commented on README.md
> + `TEST_RESULT_DB`, PG_DB, PG_USER, PG_PASSWORD, PG_HOST, PG_PORT
env variables should be enclosed by ` .

2023-06-01 11:59 UTC, Rishi16royy commented on README.md
> +  * If you want to use the Postgresql database to save your test reports, create this environment variable and set its value to postgres.
set its value to postgres --> set its value to `postgres`

2023-06-01 11:59 UTC, Rishi16royy commented on README.md
> +  * Name of the database.If this value is not provided, the default name of database will be postgres.
Space after full stop

2023-06-01 11:59 UTC, Rishi16royy commented on README.md
> +  * Name of the database.If this value is not provided, the default name of database will be postgres.
fix this in other places.

2023-06-02 04:47 UTC, Rishi16royy requested changes

2023-06-02 04:47 UTC, Rishi16royy commented on docker-compose-db.yml
> +#If you want to provide external Postgresql database then please run docker-compose-external-db.yml
change this to --> `#If you want to provide an external Postgres SQL database then remove the below lines .`

and then remove docker-compose-external-db.yml file

2023-06-02 04:47 UTC, Rishi16royy commented on engine/testreport_generator.py
>          replacement = {"test_id": test_id, "test_result": test_result, "passed_count": passed_count.__str__(),
As we are using TestUUID, we should replace TestID with TestUUID everywhere.

2023-06-02 07:09 UTC, Rishi16royy submitted a review, later dismissed

2023-06-02 15:35 UTC, hriddhighosh4 approved these changes

2023-06-02 15:35 UTC, merged